project: your-app-id

branches:
  default: develop
  files:
  - input: config/robots.template.txt
    output: static/robots.txt
  variables:
    develop:
      _version: _branch
      robots: 'Disallow: /'
    master:
      _promote: true
      #_version: ""
      robots: |
        Disallow: /admin
        Sitemap: /sitemap.xml

branch_lists:
  production:
  - master

static_dirs:
- path: static/c
  rel: static
- path: static/j
  rel: static
